### Creation of  Numpy Array

In [1]:
list=[1,2,3,4,5,6]

In [2]:
import numpy as np

In [5]:
array=np.array(list, dtype=int)
print(array)

[1 2 3 4 5 6]


In [14]:
list1=[1,2,3,4,5]
list2=[6,7,8,9,10]
list3=[11,12,13,14,15]

In [16]:
array_nested=np.array([list1,list2,list3])
print(array_nested)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [19]:
array_with_lists=np.array([[1,2,3,4],[5,6,7,8]])
print(array_with_lists)

[[1 2 3 4]
 [5 6 7 8]]


In [27]:
r=range(0,24)
print(r)

range(0, 24)


In [26]:
array_range=np.arange(24)
print(array_range)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


### Attributes of array

In [6]:
len(array)

6

In [7]:
array.ndim

1

In [8]:
array.shape

(6,)

### Reshape 

In [10]:
array2=array.reshape(3,2)
print(array2)

[[1 2]
 [3 4]
 [5 6]]


In [13]:
array3=array.reshape(2,-1) #when only one dimension is known
print(array3)

[[1 2 3]
 [4 5 6]]


In [17]:
array_nested1=array_nested.reshape(1,15)
print(array_nested1)

[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]]


In [20]:
array_with_lists.shape

(2, 4)

In [21]:
array_with_lists.shape=(4,2)
print(array_with_lists)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [22]:
array_with_lists2=array_with_lists.reshape(8,1)
print(array_with_lists2)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [28]:
array_range2=array_range.reshape(6,4,1)
print(array_range2)

[[[ 0]
  [ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]
  [ 7]]

 [[ 8]
  [ 9]
  [10]
  [11]]

 [[12]
  [13]
  [14]
  [15]]

 [[16]
  [17]
  [18]
  [19]]

 [[20]
  [21]
  [22]
  [23]]]


### Numpy Arithmetic Operations

In [29]:
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])
print(x)
print(y)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [31]:
print(x+y)
print(np.add(x,y))

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]


In [32]:
print(x-y)
print(np.subtract(x,y))

[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]


In [33]:
print(x*y)
print(np.multiply(x,y))

[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]


In [34]:
print(x/y)
print(np.divide(x,y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


### Addition over axis

In [35]:
print(np.sum(x))

10


In [36]:
print(np.sum(x,axis=0))

[4 6]


In [37]:
print(np.sum(x,axis=1))

[3 7]
