In [1]:
import numpy as np

In [3]:
v=np.array([[5,8,10],
           [9,15,19],
           [15,42,23],
           [18,5,1]])

In [4]:
v

array([[ 5,  8, 10],
       [ 9, 15, 19],
       [15, 42, 23],
       [18,  5,  1]])

In [5]:
v.shape

(4, 3)

In [6]:
weights=np.array([0.3, 0.2, 0.5])

In [7]:
np.matmul(v,weights)

array([ 8.1, 15.2, 24.4,  6.9])

In [8]:
v@weights

array([ 8.1, 15.2, 24.4,  6.9])

In [9]:
# 3D array 
arr3 = np.array([
    [[11, 12, 13], 
     [13, 14, 15]], 
    [[15, 16, 17], 
     [17, 18, 19.5]]])

In [10]:
arr3.shape

(2, 2, 3)