In [1]:
import numpy as np

### Creating Numpy arrays from Python sequences

In [2]:
array1d=np.array([1,5,6])
array1d

array([1, 5, 6])

In [3]:
a2D = np.array([[1, 2, 5], [3, 4, 6]])
a2D

array([[1, 2, 5],
       [3, 4, 6]])

In [4]:
a4D = np.array([[[[1], [2]], [[3], [4]]], [[[5], [6]], [[7], [8]]]])
a4D

array([[[[1],
         [2]],

        [[3],
         [4]]],


       [[[5],
         [6]],

        [[7],
         [8]]]])

### Creating array using intrinsic functions

### 1D arrays

In [5]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
b=np.arange(2,10)
b

array([2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
b=np.arange(2,10,1)

In [8]:
c=np.linspace(4,7,6)
c

array([4. , 4.6, 5.2, 5.8, 6.4, 7. ])

### 2D arrays

In [9]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
np.eye(3,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [12]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [13]:
np.diag([1,2,3],2)

array([[0, 0, 1, 0, 0],
       [0, 0, 0, 2, 0],
       [0, 0, 0, 0, 3],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [15]:
np.vander(np.linspace(2,4,5),2)

array([[2. , 1. ],
       [2.5, 1. ],
       [3. , 1. ],
       [3.5, 1. ],
       [4. , 1. ]])

In [16]:
np.vander(np.linspace(2,4,5),4)

array([[ 8.   ,  4.   ,  2.   ,  1.   ],
       [15.625,  6.25 ,  2.5  ,  1.   ],
       [27.   ,  9.   ,  3.   ,  1.   ],
       [42.875, 12.25 ,  3.5  ,  1.   ],
       [64.   , 16.   ,  4.   ,  1.   ]])

### General nd arrays creation

In [20]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [22]:
np.zeros((3,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [23]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [24]:
np.ones((3,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [29]:
np.random.randint(1,100,20)

array([38,  5, 85, 27, 50, 72, 58, 11, 49, 30, 43, 15, 50, 30, 91,  1, 95,
       95, 24, 30])

In [35]:
a=np.random.rand(20)
a

array([0.52886569, 0.81848938, 0.72514304, 0.9222307 , 0.79134227,
       0.49925817, 0.61416339, 0.97327031, 0.11932465, 0.85336274,
       0.59777891, 0.36624965, 0.50976059, 0.26787336, 0.51461597,
       0.13376073, 0.58847277, 0.07712075, 0.30370409, 0.7140693 ])

In [36]:
np.random.choice(a,4)

array([0.52886569, 0.61416339, 0.36624965, 0.79134227])