In [1]:
import numpy as np

### Basic Indexing

In [3]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
a[2]

2

In [5]:
a[-2]

8

In [19]:
a=a.reshape(2,5)
print(a.ndim)
print(a)

2
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [16]:
a[1,2]

7

In [20]:
a[1][2]

7

### Slicing

In [22]:
b=np.arange(20)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [23]:
b[2:10]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
b[2:20:2]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [28]:
b[-3:3:-2]

array([17, 15, 13, 11,  9,  7,  5])

In [29]:
x = np.array([[[1],[2],[3]], [[4],[5],[6]]])

In [30]:
x.shape

(2, 3, 1)

In [32]:
x[1:2]

array([[[4],
        [5],
        [6]]])

### Advanced Indexing

In [34]:
c=np.arange(40,60,2)
c

array([40, 42, 44, 46, 48, 50, 52, 54, 56, 58])

In [35]:
c[[2,3,2,4]]

array([44, 46, 44, 48])

In [36]:
c[np.array([2,3,2,4])]

array([44, 46, 44, 48])

In [38]:
y = np.arange(35).reshape(5, 7)
y

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [39]:
y[np.array([0, 2, 4]), np.array([0, 1, 2])]

array([ 0, 15, 30])

In [42]:
y[np.array([0, 2, 4]), 1:3]

array([[ 1,  2],
       [15, 16],
       [29, 30]])

In [43]:
y[:, 1:3][np.array([0, 2, 4]), :]

array([[ 1,  2],
       [15, 16],
       [29, 30]])